# Vault Package
vault_version: 1.9.3
vault_checksum: sha256:16059f245fb4df2800fe6ba320ea66aba9c2615348e37bcfd42754591a528639
vault_install_prerequisites: ["unzip", "libcap"]

# Installation
vault_binary: vault
vault_binary_folder: /usr/local/bin
vault_config_folder: /etc/vault.d
vault_data_folder: /opt/vault
vault_keys_folder: unsealKey
vault_root_token_folder: rootKey

# Service
vault_service_template: vault.service.j2
vault_service: vault.service
vault_config_template: vault.hcl.j2
vault_config: vault.hcl
vault_user: vault
vault_group: vault
vault_address: "https://127.0.0.1"
vault_port: 8200

# Certificates
vault_ssl_key_size: 4096
vault_ssl_key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
vault_ssl_cert_country_name: US
vault_ssl_cert_organization_name: VMware Inc.
vault_ssl_cert_email_address: root@localhost
vault_ssl_cert_server_hostname: localhost

folder_tmp: /tmp
folder_systemd: /etc/systemd/system
pki_ca_trust_source: /etc/pki/ca-trust/source/anchors